# Generated by Django 5.2.3 on 2025-06-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, null=True, verbose_name='ID платежа')),
                ('amount', models.IntegerField(verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание платежа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('success', 'Успешно'), ('error', 'Ошибка')], default='new', max_length=255, verbose_name='Статус платежа')),
                ('idempotence_key', models.CharField(max_length=255, null=True, verbose_name='Ключ идемпотентности')),
                ('error_description', models.CharField(max_length=255, null=True, verbose_name='Описание ошибки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
