# Generated by Django 5.2.3 on 2025-06-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_telegramuser_is_active'),
        ('transactions', '0003_alter_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.telegramuser', verbose_name='Пользователь'),
        ),
    ]
