# Generated by Django 5.1.4 on 2025-06-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(default='def50200c09396c57e7d68572d37817db14e891e92c02740bf050840453cfd9fec6145a173dbee1b04136c037e8a41baeaa15f5ccefa99ea2251f2035d8ae28bf1fd0ee4a77d30e5d7778f234192f94ca6a44e293fbb892c5bbb7ce65312eade703b4fe6cc801d1ef4dc69016a7a856add19c19853e0278518c123a6fc8e6223e611b9d58c39beab6dbbfb32a371621f62a01a095d4e2151608c7b524388b3057840e572cd830e339703070e3af0d46add9659904d644fca09c6c47d234aa1d3c721867668cd6ca57d31f9a418d8b9a0a0a985e56a794c8d7ead9148ffc41e8b7ad45797766e9adb8790015f177364800faedb17f9828ea6b3aff4a4a73db0c64ae1b1c0576abc07e29c32e2ddb8341e67f731b71622f99acf5ee028a8c46b8cc50fecca026fa8ab1f84d1410256f95a506ec349450025cbe85c057b6dbb356d305156f54ca19495f32188860f28c7221d5f3242dd0948396af32535ac44d508da3bcc84c7579a0bbe0780102ca2f2a5478d76dbeab25daca1078d3d9ccab43823e95846cb0326f28ed68ac7eeecae0b4ab7dacd34ffa792beeff3454ba875ad6bd6f4ff7fd307aaa46d1d9be324875d8392ff96b5c51cbb916c9ce418c0485eaaabf02f63a6f476f9a41a9421b9f696cd7e684b321623f6d5e174658c7f01562836b7c99c8220a7511648481bc1')),
                ('access_token', models.TextField(default='eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZjMWI2ZTAxOTI5MGNhMzkxODkxMjBmZDhkZmE3NWFlNThhYTU4ZGExYjhiMzVjZjBiMDM3YTQ2ZTJhYzlmZjg4YmFmOTg5ZjdhNzA2MGIzIn0.eyJhdWQiOiI4MWY5MTUyYi02MTk4LTQzMzItOWM3OC1iZWFjMGIwZjA3NTQiLCJqdGkiOiJmYzFiNmUwMTkyOTBjYTM5MTg5MTIwZmQ4ZGZhNzVhZTU4YWE1OGRhMWI4YjM1Y2YwYjAzN2E0NmUyYWM5ZmY4OGJhZjk4OWY3YTcwNjBiMyIsImlhdCI6MTc1MDY1NTE2NCwibmJmIjoxNzUwNjU1MTY0LCJleHAiOjE3NTA3NDE1NjQsInN1YiI6IjEyNjUwOTUwIiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMyNDk5NzgyLCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiOGNjZWRlNzYtODU5Ni00OTQyLThjOWYtM2IzMDAwN2Y2M2Y3IiwiYXBpX2RvbWFpbiI6ImFwaS1iLmFtb2NybS5ydSJ9.YU4YhCq-rl-HS8KJlhmlJ6GHFdr9MOR-nOgfFHKKbzsuopM0rhlLaBFDTeyl-mRCCrQ4Ns5yB4UKoGdOCMSz6wUnl0OOdnCi7vaVuawgaBgd_daWacPsfCCKjjMkDvjIlY5aNS7GFysElLo3WI16nFyAk5dVB4GcBGTThZ7AN-e5cdA2NL5Xvh0FswyoAqgiL9sWn55YG0hufXlqx0dPiPiyNrY-nnV2sLnyVfxsM3cARv9k5MCoaw9UCUMH0jR64s8zhx_QBTYoecGx9CXG3G_J2eqX2ALWULtIQywcXf2V7iz7hVBMAhg-OPCBS8cFcP-VT44fh9m_i4PFriv-lw')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
