# Generated by Django 5.2.1 on 2025-05-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Имя бота')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Telegram Токен')),
                ('status', models.CharField(choices=[('running', 'Запущен'), ('stopped', 'Остановлен'), ('error', 'Ошибка')], default='stopped', max_length=20, verbose_name='Статус бота')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущен:')),
                ('down_at', models.DateTimeField(blank=True, null=True, verbose_name='Остановлен:')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='PID')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
