# Generated by Django 5.2.1 on 2025-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка бота'),
        ),
    ]
