# Generated by Django 5.2.1 on 2025-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botinstance_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='PDF файл')),
                ('document_type', models.CharField(choices=[('offer', 'Оферта'), ('policy', 'Политика'), ('personal_data', 'Персональные данные'), ('notification', 'Рассылка')], max_length=20, verbose_name='Тип документа')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
