# Generated by Django 5.2.3 on 2025-06-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(blank=True, choices=[('ulan_ude', 'Улан-Удэ'), ('angarsk', 'Ангарск')], max_length=255, null=True, verbose_name='Город'),
        ),
    ]
