# Generated by Django 5.1.4 on 2025-06-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegramuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='city',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.botinstance', verbose_name='Бот'),
        ),
    ]
