# Generated by Django 5.2.3 on 2025-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_telegramuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакт'),
        ),
    ]
