# Generated by Django 5.2.3 on 2025-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_telegramuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык'),
        ),
    ]
