# Generated by Django 5.1.4 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_telegramuser_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='amo_contact_id',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='ID контакта в AmoCRM'),
        ),
    ]
