# Generated by Django 5.2.3 on 2025-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('city_id', models.IntegerField(db_column='city_id')),
            ],
            options={
                'db_table': 'markets',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'managed': False, 'verbose_name': 'Цена товара', 'verbose_name_plural': 'Цены товаров'},
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
