# Generated by Django 5.2.3 on 2025-06-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_category_market_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productprice',
            table='product_prices',
        ),
    ]
