# Generated by Django 5.2.3 on 2025-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_product_table_alter_productprice_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='city', max_length=200)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('is_public', models.BooleanField(db_column='is_public', default=False)),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'db_table': 'group_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupProductCategory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
            ],
            options={
                'db_table': 'group_product_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupProductCategorySlug',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('slug', models.CharField(db_column='slug', max_length=200)),
            ],
            options={
                'db_table': 'group_product_category_slugs',
                'managed': False,
            },
        ),
    ]
