# Generated by Django 5.2.3 on 2025-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_city_groupproduct_groupproductcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('published', models.BooleanField(blank=True, db_column='published', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'verbose_name': 'Остатки',
                'verbose_name_plural': 'Остатки',
                'db_table': 'remains',
                'managed': False,
            },
        ),
    ]
