# Generated by Django 5.2.3 on 2025-06-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_remains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('blockable_id', models.IntegerField(db_column='blockable_id', null=True)),
                ('blockable_type', models.CharField(db_column='blockable_type', max_length=200, null=True)),
                ('position', models.IntegerField(db_column='position', null=True)),
                ('content', models.TextField(db_column='content', null=True)),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'db_table': 'blocks',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Remains',
        ),
    ]
