# Generated by Django 5.2.3 on 2025-07-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('uuid', models.TextField(db_column='uuid', null=True)),
            ],
            options={
                'db_table': 'medias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('mediable_id', models.IntegerField(db_column='mediable_id', null=True)),
                ('mediable_type', models.CharField(db_column='mediable_type', max_length=200, null=True)),
            ],
            options={
                'db_table': 'mediables',
                'managed': False,
            },
        ),
    ]
