# Generated by Django 5.2.3 on 2025-06-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Сообщение рассылки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mailings/', verbose_name='Изображение рассылки')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала рассылки')),
                ('is_instant', models.BooleanField(default=False, verbose_name='Немедленная рассылка')),
                ('recipient_type', models.CharField(choices=[('NEW', 'Новые'), ('ONE', 'Разовые покупатели'), ('REGULAR', 'Постоянные')], max_length=255, verbose_name='Тип получателей')),
                ('ready_to_send', models.BooleanField(default=False, verbose_name='Готова к отправке')),
                ('is_processed', models.BooleanField(default=False, verbose_name='В обработке')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings', to='core.botinstance', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
