# Generated by Django 5.2.3 on 2025-06-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания лога')),
                ('sending_status', models.CharField(choices=[('success', 'Отправлено успешно'), ('error', 'Ошибка при отправке')], default=None, null=True, verbose_name='Статус отправки')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
    ]
