# Generated by Django 5.2.3 on 2025-06-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='theme',
            field=models.CharField(blank=True, choices=[('personal_discount', 'Персональные скидки'), ('new_bouquets', 'Новые букеты / акции'), ('holiday_offers', 'Праздничные предложения')], max_length=255, null=True, verbose_name='Тема рассылки'),
        ),
    ]
