# Generated by Django 5.2.3 on 2025-07-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки'),
        ),
    ]
