# Generated by Django 5.2.3 on 2025-07-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_button_link_mailing_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='recipient_type',
            field=models.CharField(choices=[('ALL', 'Все'), ('NEW', 'Новые'), ('ONE', 'Разовые покупатели'), ('REGULAR', 'Постоянные')], max_length=255, verbose_name='Тип получателей'),
        ),
    ]
