# Generated by Django 5.2.3 on 2025-06-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('user_contact', models.CharField(max_length=100, verbose_name='Контакт пользователя')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(max_length=100, verbose_name='Телефон получателя')),
                ('recipient_address', models.CharField(default='-', max_length=255, verbose_name='Адрес получателя')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('in_work', 'В сборке'), ('done', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=100, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('with_post_card', models.BooleanField(default=False, verbose_name='С открыткой')),
                ('post_card_text', models.TextField(blank=True, verbose_name='Текст открытки')),
                ('city', models.CharField(choices=[('ulan_ude', 'Улан-Удэ'), ('angarsk', 'Ангарск')], max_length=100, verbose_name='Город')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
