# Generated by Django 5.2.3 on 2025-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_post_card_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(null=True, verbose_name='Товар'),
        ),
    ]
