# Generated by Django 5.2.3 on 2025-06-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_telegramuser_is_active'),
        ('orders', '0003_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.telegramuser', verbose_name='Пользователь'),
        ),
    ]
