# Generated by Django 5.2.3 on 2025-06-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lead_id',
            field=models.IntegerField(null=True, verbose_name='ID сделки AmoCRM'),
        ),
    ]
