# Generated by Django 5.2.3 on 2025-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='compound',
            field=models.TextField(blank=True, null=True, verbose_name='Состав заказа'),
        ),
    ]
