# Generated by Django 5.1.4 on 2025-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lead_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID сделки AmoCRM'),
        ),
    ]
