# Generated by Django 5.1.4 on 2025-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_interval',
            field=models.CharField(blank=True, choices=[('09:00-12:00', '09:00-12:00'), ('12:00-15:00', '12:00-15:00'), ('15:00-18:00', '15:00-18:00'), ('18:00-21:00', '18:00-21:00'), ('21:00-23:00', '21:00-23:00')], max_length=100, null=True, verbose_name='Время доставки'),
        ),
    ]
